name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: '212.60.21.216'
        username: 'root'
        key: ${{ secrets.DEPLOY_KEY }}
        command_timeout: '30s'
        script: |
          cd demo
          git init
          git remote add origin https://github.com/kopollo/try-docker-ci-cd.git
          git fetch --all
          git checkout main
