name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: '212.60.21.216'
        username: 'root'
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd tests
          dir
          source myenv/bin/activate
          . run &
