name: demo test
on: [workflow_dispatch, push]
jobs:
  print: 
    runs-on: ubuntu-latest
    steps:
      - name: try ssh
        run: ssh -T root@212.60.21.216
      - name: try echo
        run: echo "KITTEN"
