name: demo test
on: [workflow_dispatch, push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ssh deploy
        env: 
          deploy_key: ${{ secrets.DEPLOY_KEY }}
        run: echo env.deploy_key
